# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://bishion.github.io
date_format: "ordinal"
title: Bishion
subtitle: "每天进步一点点"
description: "郭芳碧的个人博客"
keywords: Bishion bishion GuoFangbi
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: GuoFangbi
organization: bishion.github.io
organization_url: http://bishion.github.io
github_username: bishion
location: Shanghai, China
email: bishion@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: bishion/bishion.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: bishion
    repo: blog-comments
    oauth:
        client_id: 547cb67abc5f2ca4abea
        client_secret: 5124e3cceee4e06c0c992ef992bc0ef59b57d3e5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: bishion
    repo: blog-comments
    clientID: 547cb67abc5f2ca4abea
    clientSecret: 5124e3cceee4e06c0c992ef992bc0ef59b57d3e5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-113874603-1
